## Class 2

###### 1. The transpose of a vector and a matrix
###### 2. Product between matrices and vectors
###### 3. Scalar product to compute the value of a portfolio
###### 4. Compute determinant of a matrix
###### 5. Compute the rank of a matrix
###### 6. Compute the inverse of a matrix

In [1]:
import numpy as np

### 1. The transpose of a vector and a matrix

In [2]:
# Creating a new vector 'x' with 4 elements
# This is a column vector (4x1 matrix)
x = np.array([[0],[3],[5],[1]])
print(x)  # Output: column vector

[[0]
 [3]
 [5]
 [1]]


In [3]:
# Transpose of the vector 'x'
# The transpose changes the column vector into a row vector
x_T = x.transpose()
print(x_T)  # Output: row vector

[[0 3 5 1]]


In [4]:
# Creating a new matrix 'A' with 2 rows and 4 columns
A = np.array([[8,5,0,1],[4,2,0,2]])
print(A)  # Output: matrix with 2 rows and 4 columns

[[8 5 0 1]
 [4 2 0 2]]


In [5]:
# Transpose of the matrix 'A'
# The transpose changes rows into columns and vice versa
A_T = A.transpose()
print(A_T)  # Output: matrix with 4 rows and 2 columns

[[8 4]
 [5 2]
 [0 0]
 [1 2]]


### 2. Product between matrices and vectors

###### A. Product between 2 vectors

In [6]:
# creating a new vector y

y = np.array([[1],[0],[4],[2]])
print(y)

[[1]
 [0]
 [4]
 [2]]


In [7]:
# x and y are two column vectors (4x1). We can multiply them in two ways:
# 1. x@y' is a 4x4 matrix
# 2. x'@y is a number (1x1)

y_T = y.transpose()
print(x@y_T)
print(x_T@y)

[[ 0  0  0  0]
 [ 3  0 12  6]
 [ 5  0 20 10]
 [ 1  0  4  2]]
[[22]]


###### B. Product between 2 matrices

In [8]:
# Creating a new matrix B

B = np.array([[0,2,0,1],[3,3,0,6]])
print(B)

[[0 2 0 1]
 [3 3 0 6]]


In [9]:
# A and B are two matrices (2x4). We can multiply them in two ways:
# 1. A@B' is a 2x2 matrix
# 2. A'@B is a 4x4 matrix

print(A.shape)
print(B.shape)
B_T = B.transpose()

(2, 4)
(2, 4)


In [10]:
print(A@B_T)
print(A_T@B)

[[11 45]
 [ 6 30]]
[[12 28  0 32]
 [ 6 16  0 17]
 [ 0  0  0  0]
 [ 6  8  0 13]]


###### C. Product between a matrix and a vector

In [11]:
print(A.shape)
print(x.shape)

(2, 4)
(4, 1)


In [12]:
# we can compute A@x and we obtain a column vector (2x1)
print(A@x)

[[16]
 [ 8]]


### 3. Scalar product to compute the value of a portfolio

In [13]:
# Example 13 from the slides
a = np.array([[4],[2],[1]]) #number of shares of the assets
p = np.array([[100],[80],[120]]) #market value
print(a)
print(p)

[[4]
 [2]
 [1]]
[[100]
 [ 80]
 [120]]


In [14]:
# value of portfolio
a_T = a.transpose()
V = a_T@p
print(V)

[[680]]


In [15]:
# value of portfolio using function inner
# pay attention to apply inner function a and p be row vectors
a1 = np.array([4,2,1]) #number of shares of the assets
p1 = np.array([100,80,120]) #market value
V_1 = np.inner(a1,p1)
print(V_1)

680


In [16]:
# now create a function

def value_portfolio (a,p):
    dim_a = a.shape
    dim_p = p.shape
    if dim_a == dim_p:
        return np.inner(a,p)
    else:
        return "The dimension of 2 vectors are different"

In [17]:
# value of portfolio
value_portfolio(a1,p1)

680

In [18]:
# try with higher dimension
a2 = np.array ([1,3,2,5,6,0.5,2])
p2 = np.array ([100,106,110,99,120,98,82])

In [19]:
# value of portfolio
value_portfolio(a2,p2)

2066.0

In [20]:
# try with a mistake
a3 = np.array ([1,3,2,5,6,0.5])
p3 = np.array ([100,106,110,99,120,98,82])
print(a3.shape)
print(p3.shape)

(6,)
(7,)


In [21]:
# value of portfolio
value_portfolio(a3,p3)

'The dimension of 2 vectors are different'

### 4. Compute the determinant of a matrix

In [22]:
# Of course, we can only compute the determinant of square matrices (from example 14)

A = np.array([[0,1],[2,3]]) 
print(A)    

print(np.linalg.det(A))  

[[0 1]
 [2 3]]
-2.0


In [23]:
B = np.array([[1,1],[2,2]]) 
print(B)    

print(np.linalg.det(B))

[[1 1]
 [2 2]]
0.0


In [24]:
# higher dimension
C = np.array([[1,2,-1],[2,0,4],[-1,4,3]]) 
print(C)    

print(np.linalg.det(C))

[[ 1  2 -1]
 [ 2  0  4]
 [-1  4  3]]
-43.99999999999999


In [25]:
# diagonal matrix
D = np.array([[1,0,0],[0,2,0],[0,0,1]]) 
print(D)    

print(np.linalg.det(D))

[[1 0 0]
 [0 2 0]
 [0 0 1]]
2.0


In [26]:
E = np.array([[4,2,2],[2,1,1],[3,0,5]]) 
print(E)    

print(np.linalg.det(E))

[[4 2 2]
 [2 1 1]
 [3 0 5]]
0.0


In [27]:
# triangular matrix
F = np.array([[1,0,0],[1,1,0],[2,2,1]]) 
print(F)    

print(np.linalg.det(F))

[[1 0 0]
 [1 1 0]
 [2 2 1]]
1.0


### 5. Compute the rank of a matrix

In [28]:
print(A)
print(np.linalg.det(A)) # the determinant is different from zero, it is a full rank matrix

[[0 1]
 [2 3]]
-2.0


In [29]:
# check the rank of matrix A
print(np.linalg.matrix_rank(A))

2


In [30]:
print(C)
print(np.linalg.det(C)) # the determinant is different from zero, it is a full rank matrix

[[ 1  2 -1]
 [ 2  0  4]
 [-1  4  3]]
-43.99999999999999


In [31]:
# check the rank of matrix C
print(np.linalg.matrix_rank(C))

3


In [32]:
print(E)
print(np.linalg.det(E)) # the determinant is equal to zero, E is not a full rank matrix

[[4 2 2]
 [2 1 1]
 [3 0 5]]
0.0


In [32]:
# check the rank of matrix E
print(np.linalg.matrix_rank(E))

2


In [33]:
# create a not square matrix
S = np.array([[2,4,0],[3,4,2]])
print(S)

[[2 4 0]
 [3 4 2]]


In [34]:
# compute the rank of S
print(np.linalg.matrix_rank(S))

2


### 6. Compute the inverse of a matrix

In [35]:
print(C)
print(np.linalg.det(C)) # the determinant is different from zero, is a full rank matrix, we can compute the inverse

[[ 1  2 -1]
 [ 2  0  4]
 [-1  4  3]]
-43.99999999999999


In [36]:
print(np.linalg.inv(C))

[[ 0.36363636  0.22727273 -0.18181818]
 [ 0.22727273 -0.04545455  0.13636364]
 [-0.18181818  0.13636364  0.09090909]]


In [37]:
print(E)
print(np.linalg.det(E)) # the determinant is equal to zero, E is not a full rank matrix. We cannot compute the inverse

[[4 2 2]
 [2 1 1]
 [3 0 5]]
0.0


In [38]:
try:
    print(np.linalg.inv(E))
except:
    print("We cannot compute the inverse")

We cannot compute the inverse


In [40]:
# create a function
def inverse(A):
    num_rows = A.shape[0]
    num_cols = A.shape[1]
    if num_rows == num_cols:
        det_A = np.linalg.det(A)
        if det_A != 0:
            return np.linalg.inv(A)
        else:
            return "The matrix is a square matrix but the determinant is equal to zero. The inverse doesn't exist"
    else:
        return "The matrix is not a square matrix, then it is impossible to compute the inverse"

In [39]:
# try the function with the matrix C
print(C)
inverse(C)

[[ 1  2 -1]
 [ 2  0  4]
 [-1  4  3]]


NameError: name 'inverse' is not defined

In [42]:
# try the function with the matrix E
print(E)
inverse(E)

[[4 2 2]
 [2 1 1]
 [3 0 5]]


"The matrix is a square matrix but the determinant is equal to zero. The inverse doesn't exist"

In [43]:
# try the function with the matrix S
print(S)
inverse(S)

[[2 4 0]
 [3 4 2]]


'The matrix is not a square matrix, then it is impossible to compute the inverse'

In [44]:
# Let's verify that A*A^(-1)=A^(-1)*A=I

A = np.array([[2,4,6],[1,0,3],[0,1,1]])
print(A) 

Ainv = inverse(A)
print(A@Ainv)
print(Ainv@A)

[[2 4 6]
 [1 0 3]
 [0 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
