# Introduction to Python Variables and Basic Functions

In this notebook we will explore basic Python concepts like variables, input/output, and string manipulation. 


In [1]:
# The print() function displays the message inside the parentheses to the console.
print('Hello world') 

Hello world


### Variable Assignment, Int Variables and Printing

A **variable** is a named storage location in memory where you can store different types of data, such as numbers, text, or boolean values. 

In Python:
- Variables are dynamically typed, meaning you don't need to declare the type before using them.
- You can change the value of a variable by reassigning it.

In [2]:
temperature = 28  # Assigning an integer number (we're declaring an int variable)
temperature = 30   # Updating the value of the variable
print(temperature)  # This will print the current value of the variable (30)

# This prints the word 'temperature' itself as a string, not the value of the variable
print("temperature")


30
temperature


### Floating-Point Variables

A **floating-point number** (or float) is a number that contains decimal points. This allows you to store more precise values, like measurements or currency.

Floats are automatically recognized in Python, and you don't need to specify the type.# Assigning a floating-point number to a variable

In [3]:
lower_temperature = 19.95  # Assigning a float value
print(lower_temperature)  # Printing the value of the floating point variable

19.95


### String Variables

A **string** is a sequence of characters used to represent text. In Python, strings are enclosed in either single quotes (`' '`) or double quotes (`" "`).# Assigning a string to a variable

In [4]:
university = "Luiss"  # Assigning a string value to the variable
print(university)  # Printing the value stored in the variable 


Luiss


### Boolean Variables

A **boolean** is a data type that can hold only one of two values: `True` or `False`. Booleans are often used to represent the outcome of a comparison or the state of a condition.

Booleans are useful in decision-making processes and conditions in your code.


In [29]:
is_online = False  # Assigning a boolean value (True or False)
print(is_online)  # Printing the boolean value (in this case, False)


False


### Getting Input from the User

The **`input()` function** is used to prompt the user to enter some data. The data entered by the user is always returned as a string, even if they enter a number.

In the next cell:
- We prompt the user to enter their name using `input()`.
- The entered value is stored in the variable `name`.
- We then print the entered name using `print()`.
- Finally, we print the fixed string `"Michela"` to show how we can print predefined text, unrelated to the user’s input.


In [7]:
name = input("What is your name? ")  # The input function displays a prompt and waits for the user to input a value
print(name)  # Printing the name entered by the user

# Printing a fixed string
print("Luke")  # This will always print the string "Luke" regardless of what the user enters


What is your name?  Marco


Marco
Luke


### String Concatenation

**String concatenation** is the process of combining two or more strings into one. In Python, this is done using the `+` operator.

This code allows us to create a personalized greeting for the user.


# Asking for the user's name again and greeting them using string concatenation

name = input("What is your name? ")  # Asking for user input
print("Hello " + name)  # Concatenating the greeting with the user's input


### Mathematical Operations

Python supports various mathematical operations. Some of the common ones are:
- Addition (`+`)
- Subtraction (`-`)
- Multiplication (`*`)
- Division (`/`)

There are also more advanced operators:
- Modulus (`%`): Gives the remainder of a division.
- Exponentiation (`**`): Raises one number to the power of another.

Let's see some examples of these operations.


In [48]:
# Basic mathematical operations
print(3 + 7)  # Addition: 3 + 7 = 10
print(10 - 9)  # Subtraction: 10 - 9 = 1
print(8 * 2)  # Multiplication: 8 * 2 = 16

# Division (returns a float)
print(4 / 3)  # Float result of division: 4 / 3

# Integer division using floor division
print(4 // 3)  # Integer division (discarding remainder): 4 // 3

# Modulus (remainder of division)
print(10 % 3)  # Modulus: 10 % 3 gives the remainder, which is 1

# Exponentiation (power)
print(10 ** 3)  # Exponentiation: 10 raised to the power of 3 = 1000


10
1
16
1.3333333333333333
1
1
1000


### Augmented Assignment Operators

Augmented assignment operators allow you to perform a mathematical operation and assignment in one step. Common augmented assignment operators include:
- `+=`: Adds and assigns the result.
- `-=`: Subtracts and assigns the result.
- `*=`: Multiplies and assigns the result.
- `/=`: Divides and assigns the result.

In the next cell, we will demonstrate the `+=` operator, which adds a value to the variable and updates it in one step.


In [8]:
# Augmented assignment operation

X = 10  # Initial value of X
X += 3  # Equivalent to X = X + 3, this adds 3 to X
print(X)  # This will print 13, the new value of X


13


### Type Conversion

In Python, it is possible to convert input from a string to an integer using the `int()` function.

This code prompts the user to enter their birth year, converts the input (a string) into an integer, and calculates their age by subtracting the birth year from 2024. The result is then printed to display the user's age.

In [10]:
## # Getting the birth year from the user as input (which will be a string)
birth_year = input("Enter your birth year: ")

# Converting the birth year to an integer and calculating age
age = 2024 - int(birth_year)  # Subtracting the birth year from the current year (2024)
print(age)  # Printing the calculated age


Enter your birth year:  11021976


-11019952


### Comparison Operators in Python

Python provides comparison operators to compare values. These operators can return boolean values (`True` or `False`) based on the result of the comparison.

- **Greater than (`>`)**: Returns `True` if the left-hand operand is greater than the right-hand operand.
- **Less than (`<`)**: Returns `True` if the left-hand operand is less than the right-hand operand.
- **Equality (`==`)**: Returns `True` if both operands are equal.
- **Inequality (`!=`)**: Returns `True` if both operands are not equal.


In [42]:
# Greater than comparison
X = 1 > 2  # This will evaluate to False because 1 is not greater than 2
print(X)

# Less than comparison
Y = 3 < 8  # This will evaluate to True because 3 is less than 8
print(Y)

# Equality comparison
Z = 5 == 6  # This will evaluate to False because 5 is not equal to 6
print(Z)

# Inequality comparison
H = 7 != 9  # This will evaluate to True because 7 is not equal to 9
print(H)

False
True
False
True


### Working with Lists in Python

A **list** is a collection of items, which can be of different types. Lists are ordered and mutable, meaning the elements can be changed after the list is created.



In [69]:
# Creating a list of names
names = ["Anna", "Chiara", "Elena"]  # Defining a list of strings
print(names)  # Printing the entire list

['Anna', 'Chiara', 'Elena']


In [1]:
# Example of a list of numbers
numbers = [5, 12, 8, 3, 25, 7]

# Printing the list
print(numbers)

print(len(numbers)) # len() is a function that returns the lenght of the list

[5, 12, 8, 3, 25, 7]
6


# Numpy
NumPy (Numerical Python) is a library for handling arrays and performing mathematical and logical operations on them efficiently. It's widely used for scientific computing and is the foundation for many other Python libraries.

# Importing numpy
To use Numpy in your code, you typically import it as follows:

In [6]:
import numpy as np #np is a shorhand


In [10]:
arr=np.array([1,2,3,4,5]) #create an 1D array

matrix=np.array([[1,2,3],[4,5,6]]) #create a 2D array (Matrix)

print(arr)
print(matrix)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Array operations

In [13]:
a=np.array([1,2,3])
b=np.array([5,6,7])

sum_arr=a+b #sum of elemets

prod_arr=a*b #product of the elements

print("sum", sum_arr)
print("product", prod_arr)

sum [ 6  8 10]
product [ 5 12 21]
